version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    ports:
      - '5432:5432'
    volumes:
      - ~/apps/mongo:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "8910:8910"
    volumes:
      - ~/apps/web:/app
    environment:
      - DATABASE_URL=postgresql://other@localhost/otherdb?connect_timeout=10&application_name=myapp
      - PRISMA_HIDE_UPDATE_MESSAGE=true
      - SESSION_SECRET=pd8RNxZJ9foEvWTAjJo5V34YrHQidsTb3HDZ62zbiJpQ8J6vV2rVWyCnYgBY3ouj
    depends_on:
      db:
        condition: service_started
      api:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl", "-f", "http://localhost:8910/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8911:8911"
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_healthy
    volumes:
      - ~/apps/api:/app
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl", "--request", "POST", "--header", "content-type: application/json", "--url", "http://localhost:8911/api/graphql", "--data", '{"query":"{ redwood { version } }"}']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s


